### ISSUE TITLE
mount and umount

### ISSUE THREAD

**Issue by Cyber-SiKu** [opencurve/curveadm#3]
1. When mounting, the format of mountpoint should be: [hostname:mountpoint], but when using curveadm mount, the format of mountpoint becomes [a string of numbers: /usr/local/curvefs/client/mnt]
2. Although unmounting with umount is successful, the mount point is unavailable and an error output appears.
![image](https://user-images.githubusercontent.com/15775037/141949032-8e64f890-ddb2-48d1-9ff2-f155028f0295.png)
![image](https://user-images.githubusercontent.com/15775037/141950257-cb8c2956-4cb9-4ac2-932c-a99796de83a2.png)
3. Although it shows that umount is successfully uninstalled, the mount point is still inaccessible, and the error output is as follows:
![image](https://user-images.githubusercontent.com/15775037/141951097-390414ac-c610-4bcb-aaac-611334784b9e.png)
4. At this time, deleting fs will fail, mds log shows fs_busy, you need to use the tool umount, you can delete successfully at this time.

**Comment by aspirer** [comment]
The bucket name in config file isn't exists on s3, and the docker image isn't published by curve.
So this issue is invalid.

**Comment by Cyber-SiKu** [comment]
4. still work

**Comment by Wine93** [comment]
The `umount` command will execute the below two operations:

* stop `fuse` process
* remove the container which `fuse` occupied 

So as you said, there is no exception handling.

On the other hand, i think we should use `fusemount` to `umount` filesystem instead of stop `fuse` process, welcome to submit a PR to solve this problem :)

**Comment by Wine93** [comment]
closing it
